# Generated by Django 6.0.2 on 2026-04-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='P_Desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='P_End',
            new_name='End',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='P_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='P_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='P_Start',
            new_name='Start',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='P_Status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='U_Dept',
            new_name='Dept',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='U_JoinDate',
            new_name='JoinDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='U_Phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='U_Post',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='U_Role',
            new_name='Role',
        ),
    ]
