# Generated by Django 6.0.2 on 2026-04-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_p_desc_project_desc_rename_p_end_project_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_assignment',
            old_name='PA_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='T_End',
            new_name='End',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='T_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='T_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='T_Start',
            new_name='Start',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='T_Status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='task_comment',
            old_name='C_DateTime',
            new_name='DateTime',
        ),
        migrations.RenameField(
            model_name='task_comment',
            old_name='C_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='task_comment',
            old_name='C_Text',
            new_name='Text',
        ),
    ]
