# Generated by Django 6.0.2 on 2026-04-10 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_pa_id_project_assignment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Assigned_To',
        ),
        migrations.AddField(
            model_name='task',
            name='Assigned_To',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
