# Generated by Django 6.0.2 on 2026-04-15 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='Assigned_To',
        ),
        migrations.AlterField(
            model_name='task',
            name='P_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='task_comment',
            name='T_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.task'),
        ),
        migrations.DeleteModel(
            name='Project_Assignment',
        ),
        migrations.AddField(
            model_name='task',
            name='Assigned_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
