# Generated by Django 6.0.2 on 2026-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_project_members_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='task_comment',
            name='ID',
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=50),
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task_comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AddField(
            model_name='task_comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
