# Generated by Django 6.0.2 on 2026-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_user_options_remove_task_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='End',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
