# Generated by Django 6.0.2 on 2026-05-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_task_end_alter_task_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(upload_to='project_files/')),
                ('Uploaded_At', models.DateTimeField(auto_now_add=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myapp.project')),
            ],
        ),
    ]
